version: "3.3"

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    restart: always
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker-data-volumes/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
    networks:
      - efk_net

  fluentd:
    build: ./fluentd
    restart: always
    volumes:
      - ./fluentd/etc:/fluentd/etc
    ports:
      - 24224:24224
    networks:
      - efk_net

  kibana:
    image: ${KIBANA_IMAGE}
    restart: always
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - efk_net

networks:
  efk_net:
    driver: bridge
