version: '3.2'
services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    restart: always
    environment:
      - 'node.name=truongbb-es'
      - 'discovery.type=single-node'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'network.host=0.0.0.0'
      - 'xpack.security.enabled=false'
    ports:
      - 9200:9200
#      - 9300:9300
    networks:
      - efk_jaeger
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: ${LOG_OPT_TAG_PREFIX}.efk.elasticsearch

  kibana:
    image: ${KIBANA_IMAGE}
    restart: always
    ports:
      - 5601:5601
    networks:
      - efk_jaeger
    depends_on:
      - elasticsearch
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: ${LOG_OPT_TAG_PREFIX}.efk.kibana
    environment:
      - 'ELASTICSEARCH_URL=http://elasticsearch:9200'

  fluentd:
    image: ${FLUENTD_IMAGE}
    ports:
      - 24224:24224
    volumes:
      - './fluentd/etc:/fluentd/etc'
    networks:
      - efk_jaeger
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "5"


networks:
  efk_jaeger:
    driver: bridge
