version: '3.3'

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    restart: always
    environment:
      - 'node.name=truongbb-es'
      - 'discovery.type=single-node'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'network.host=0.0.0.0'
      - 'xpack.security.enabled=false'
    ports:
      - 9200:9200
    networks:
      - efk_net

  fluentd:
    build: ./fluentd
    restart: always
    volumes:
      - ./fluentd/etc:/fluentd/etc
    ports:
      - 24224:24224
    networks:
      - efk_net

  kibana:
    image: ${KIBANA_IMAGE}
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - 'ELASTICSEARCH_URL: http://elasticsearch:9200'
    ports:
      - 5601:5601
    networks:
      - efk_net

networks:
  efk_net:
    driver: bridge